const shopActionTypes = {
    FETCHING_SHOP_DETAILS:'FETCHING_SHOP_DETAILS',
    FETCHING_SHOP_DETAILS_SUCCESS:'FETCHING_SHOP_DETAILS_SUCCESS',
    FETCHING_SHOP_DETAILS_FAILURE:'FETCHING_SHOP_DETAILS_FAILURE',
    ADDING_SHOP_DETAILS:'ADDING_SHOP_DETAILS',
    ADDING_SHOP_DETAILS_SUCCESS:'ADDING_SHOP_DETAILS_SUCCESS',
    ADDING_SHOP_DETAILS_FAILURE:'ADDING_SHOP_DETAILS_FAILURE',
}

export default shopActionTypes;