const productActionTypes = {
    FETCHING_PRODUCT_DETAILS:'FETCHING_PRODUCT_DETAILS',
    FETCHING_PRODUCT_DETAILS_SUCCESS:'FETCHING_PRODUCT_DETAILS_SUCCESS',
    FETCHING_PRODUCT_DETAILS_FAILURE:'FETCHING_PRODUCT_DETAILS_FAILURE',
    ADDING_PRODUCT_DETAILS:'ADDING_PRODUCT_DETAILS',
    ADDING_PRODUCT_DETAILS_SUCCESS:'ADDING_PRODUCT_DETAILS_SUCCESS',
    ADDING_PRODUCT_DETAILS_FAILURE:'ADDING_PRODUCT_DETAILS_FAILURE'
}
export default productActionTypes;