const userActionTypes = {
    FETCHING_USER_DETAILS:'FETCH_USER_DETAILS',
    FETCHING_USER_DETAILS_SUCCESSS:'FETCHING_USER_DETAILS_SUCCESS',
    FETCHING_USER_DETAILS_FAILURE:'FETCHING_USER_DETAILS_FAILURE',
}

export default userActionTypes;