const sellerActionTypes = {
    SELLER_SIGN_IN:'SELLER_SIGN_IN',
    SELLER_SIGN_IN_SUCCESS:'SELLER_SIGN_IN_SUCCESS',
    SELLER_SIGN_IN_FAILURE:'SELLER_SIGN_IN_FAILURE',
    SELLER_REGISTRATION:'SELLER_REGISTRATION',
    SELLER_REGISTRATION_SUCCESS:'SELLER_REGISTRATION_SUCCESS',
    SELLER_REGISTRATION_FAILURE:'SELLER_REGISTRATION_FAILURE'
}

export default sellerActionTypes;