const buyerActionTypes = {
    BUYER_SIGN_IN:'BUYER_SIGN_IN',
    BUYER_SIGN_IN_SUCCESS:'BUYER_SIGN_IN_SUCCESS',
    BUYER_SIGN_IN_FAILURE:'BUYER_SIGN_IN_FAILURE',
    FETCHING_NEARBY_SHOPS:'FETCHING_NEARBY_SHOPS',
    FETCHING_NEARBY_SHOPS_SUCCESS:'FETCHING_NEARBY_SHOPS_SUCCESS',
    FETCHING_NEARBY_SHOPS_FAILURE:'FETCHING_NEARBY_SHOPS_FAILURE',
    FETCHING_PRODUCTS_DETAILS:'FETCHING_PRODUCTS_DETAILS',
    FETCHING_PRODUCTS_DETAILS_SUCCESS:'FETCHING_PRODUCTS_DETAILS_SUCCESS',
    FETCHING_PRODUCTS_DETAILS_FAILURE:'FETCHING_PRODUCTS_DETAILS_FAILURE',
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    FETCHING_BUYER_ORDERS:'FETCHING_BUYER_ORDERS',
    FETCHING_BUYER_ORDERS_SUCCESS:'FETCHING_BUYER_ORDERS_SUCCESS',
    FETCHING_BUYER_ORDERS_FAILURE:'FETCHING_BUYER_ORDERS_FAILURE',
    CLEAR_CART:'CLEAR_CART'
}

export default buyerActionTypes;