const buyerActionTypes = {
    BUYER_SIGN_IN:'BUYER_SIGN_IN',
    BUYER_SIGN_IN_SUCCESS:'BUYER_SIGN_IN_SUCCESS',
    BUYER_SIGN_IN_FAILURE:'BUYER_SIGN_IN_FAILURE',
    FETCHING_NEARBY_SHOPS:'FETCHING_NEARBY_SHOPS',
    FETCHING_NEARBY_SHOPS_SUCCESS:'FETCHING_NEARBY_SHOPS_SUCCESS',
    FETCHING_NEARBY_SHOPS_FAILURE:'FETCHING_NEARBY_SHOPS_FAILURE',
    FETCHING_PRODUCTS_DETAILS:'FETCHING_PRODUCTS_DETAILS',
    FETCHING_PRODUCTS_DETAILS_SUCCESS:'FETCHING_PRODUCTS_DETAILS_SUCCESS',
    FETCHING_PRODUCTS_DETAILS_FAILURE:'FETCHING_PRODUCTS_DETAILS_FAILURE'
}

export default buyerActionTypes;